name: AceEmployments
version: '${version}'
main: net.refractored.aceemployments.AceEmployments
api-version: '1.21'
authors: [refractored]
description: "Players can create employment listings for items in minecraft."
database: true
depend: [Vault]
softdepend:
  - ItemsAdder
  - Essentials
  - eco
  - EcoItems
  - RedisChat
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.0.0
  - com.j256.ormlite:ormlite-core:5.6
  - com.j256.ormlite:ormlite-jdbc:5.6
commands:
  employ:
    description: "Main command for AceEmployments"
    aliases: [emp, employments]
permissions:
  aceemployments.create:
    description: "Create new employment listings."
    default: true
  aceemployments.browse:
    description: "Browse available employment listings."
    default: true
  aceemployments.myjobs:
    description: "View your own employment listings."
    default: true
  aceemployments.contribute:
    description: "Contribute items to job listings."
    default: true
  aceemployments.subscribe:
    description: "Subscribe to item notifications."
    default: true
  aceemployments.notifier:
    description: "Set notification preferences."
    default: true
  aceemployments.container:
    description: "Access your item container."
    default: true
  aceemployments.admin.reload:
    description: "Reload the plugin configuration."
    default: op
  aceemployments.admin.delist:
    description: "Cancel all listings for a player."
    default: op